# Generated by Django 3.1.2 on 2021-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblcourseinfo',
            fields=[
                ('courseinfoid', models.IntegerField(db_column='CourseInfoId', primary_key=True, serialize=False)),
                ('courseid', models.IntegerField(db_column='CourseId', unique=True)),
                ('coursename', models.TextField(blank=True, db_column='CourseName', null=True)),
                ('subjectid', models.IntegerField(db_column='SubjectId')),
                ('subjectname', models.TextField(db_column='SubjectName')),
                ('skillid', models.IntegerField(db_column='SkillId')),
                ('skillname', models.TextField(db_column='SkillName')),
                ('providerid', models.IntegerField(db_column='ProviderId')),
                ('providername', models.TextField(db_column='ProviderName')),
                ('coursepatternid', models.IntegerField(db_column='CoursePatternId')),
                ('createdby', models.IntegerField(db_column='CreatedBy')),
                ('updatedby', models.IntegerField(db_column='UpdatedBy')),
                ('createdon', models.DateTimeField(db_column='CreatedOn')),
                ('updatedon', models.DateTimeField(db_column='UpdatedOn')),
            ],
            options={
                'db_table': 'tblCourseInfo',
            },
        ),
        migrations.CreateModel(
            name='Tblcourseratings',
            fields=[
                ('courseratingid', models.IntegerField(db_column='CourseRatingId', primary_key=True, serialize=False)),
                ('courseid', models.IntegerField(db_column='CourseId')),
                ('rating', models.DecimalField(db_column='Rating', decimal_places=2, max_digits=4)),
                ('createdby', models.IntegerField(db_column='CreatedBy')),
                ('updatedby', models.IntegerField(db_column='UpdatedBy')),
                ('createdon', models.DateTimeField(db_column='CreatedOn')),
                ('updatedon', models.DateTimeField(db_column='UpdatedOn')),
            ],
            options={
                'db_table': 'tblCourseRatings',
                'unique_together': {('createdby', 'courseid')},
            },
        ),
    ]
